server:
  port: 8081    # 프로필마다 포트번호 다르게 설정

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        type:
          descriptor:
            sql: trace

  output:
    ansi:
      enabled: always

  config:
    import:
      - application-h2.yml
      - application-jwt.yml

logging:
  level:
    com.springsecurity: DEBUG