server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    com.springsecurity: DEBUG